[platformio]
default_envs = esp32-s3-supermini

[env:esp32-s3-supermini]
platform = espressif32
board = esp32-s3-supermini-custom
framework = arduino
upload_protocol = esptool
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  ewpa/LibSSH-ESP32@^5.5.1
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_MODE=0
  -UARDUINO_USB_CDC_ON_BOOT
  -DARDUINO_USB_CDC_ON_BOOT=0
build_src_filter =
  +<main.cpp>
  -<diag_main.cpp>

[env:esp32-s3-supermini-diag]
platform = espressif32
board = esp32-s3-supermini-custom
framework = arduino
upload_protocol = esptool
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
  -DCORE_DEBUG_LEVEL=3
build_src_filter =
  +<diag_main.cpp>
  -<main.cpp>
